In [1]:
import numpy as np
import pandas as pd

In [2]:
books = pd.read_csv('Books.csv', low_memory=False)
ratings = pd.read_csv('Ratings.csv')
users = pd.read_csv('Users.csv')

In [3]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [4]:
users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [5]:
ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [6]:
print(books.shape)
print(ratings.shape)
print(users.shape)

(271360, 8)
(1149780, 3)
(278858, 3)

In [7]:
books.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            1
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [8]:
users.isnull().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [9]:
ratings.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [10]:
books.duplicated().sum()

0

In [11]:
ratings.duplicated().sum()

0

In [12]:
users.duplicated().sum()

0

# Popularity Based Recommendation System

In [13]:
# Merge ratings and books dataframes

In [14]:
df = ratings.merge(books, on='ISBN')

In [15]:
num_df = df.groupby('Book-Title')['Book-Rating'].count().reset_index()

In [16]:
num_df.rename(columns = {'Book-Rating':'Num-Rating'},inplace=True)

In [17]:
num_df

                                               Book-Title  Num-Rating
0        A Light in the Storm: The Civil War Diary of ...           4
1                                   Always Have Popsicles           1
2                    Apple Magic (The Collector's series)           1
3        Ask Lily (Young Women of Faith: Lily Series, ...           1
4        Beyond IBM: Leadership Marketing and Finance ...           1
...                                                   ...         ...
241066                                      Ã?Â?lpiraten.           2
241067                     Ã?Â?rger mit Produkt X. Roman.           4
241068                                Ã?Â?sterlich leben.           1
241069                              Ã?Â?stlich der Berge.           3
241070                                  Ã?Â?thique en toc           2

[241071 rows x 2 columns]

In [18]:
avg_df = df.groupby('Book-Title')['Book-Rating'].mean().reset_index()
avg_df.rename(columns = {'Book-Rating':'avg-Rating'},inplace=True)
avg_df

                                               Book-Title  avg-Rating
0        A Light in the Storm: The Civil War Diary of ...    2.250000
1                                   Always Have Popsicles    0.000000
2                    Apple Magic (The Collector's series)    0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...    8.000000
4        Beyond IBM: Leadership Marketing and Finance ...    0.000000
...                                                   ...         ...
241066                                      Ã?Â?lpiraten.    0.000000
241067                     Ã?Â?rger mit Produkt X. Roman.    5.250000
241068                                Ã?Â?sterlich leben.    7.000000
241069                              Ã?Â?stlich der Berge.    2.666667
241070                                  Ã?Â?thique en toc    4.000000

[241071 rows x 2 columns]

In [19]:
popularity_df = avg_df.merge(num_df, on='Book-Title')

In [20]:
popularity_df = popularity_df[popularity_df['Num-Rating']>450].sort_values('avg-Rating', ascending=False)

In [21]:
popularity_df = popularity_df.head(50)

In [22]:
popularity_index = popularity_df.merge(books, on='Book-Title')

In [23]:
popularity_index = popularity_index.drop_duplicates('Book-Title')

In [24]:
popularity_index.shape

(50, 10)

In [25]:
popularity_rs = popularity_index[['Book-Title','Book-Author','Num-Rating', 'avg-Rating', 'Image-URL-M']]

In [26]:
popularity_rs

,Book-Title,Book-Author,Num-Rating,avg-Rating,Image-URL-M
0,Harry Potter and the Chamber of Secrets (Book 2),J. K. Rowling,556,5.183453,http://images.amazon.com/images/P/0439064872.0...
3,Harry Potter and the Sorcerer's Stone (Harry P...,J. K. Rowling,575,4.895652,http://images.amazon.com/images/P/059035342X.0...
5,To Kill a Mockingbird,Harper Lee,510,4.700000,http://images.amazon.com/images/P/0446310786.0...
13,The Da Vinci Code,Dan Brown,898,4.642539,http://images.amazon.com/images/P/0385504209.0...
19,The Lovely Bones: A Novel,Alice Sebold,1295,4.468726,http://images.amazon.com/images/P/0316666343.0...
20,The Secret Life of Bees,Sue Monk Kidd,774,4.447028,http://images.amazon.com/images/P/0142001740.0...
26,"Tuesdays with Morrie: An Old Man, a Young Man,...",MITCH ALBOM,493,4.354970,http://images.amazon.com/images/P/0385484518.0...
29,The Red Tent (Bestselling Backlist),Anita Diamant,723,4.334716,http://images.amazon.com/images/P/0312195516.0...
30,Girl with a Pearl Earring,Tracy Chevalier,526,4.218631,http://images.amazon.com/images/P/0452282152.0...
31,Where the Heart Is (Oprah's Book Club (Paperba...,Billie Letts,585,4.105983,http://images.amazon.com/images/P/0446672211.0...
32,Life of Pi,Yann Martel,664,4.088855,http://images.amazon.com/images/P/0151008116.0...
36,Good in Bed,Jennifer Weiner,490,4.055102,http://images.amazon.com/images/P/0743418174.0...
38,Suzanne's Diary for Nicholas,James Patterson,457,3.820569,http://images.amazon.com/images/P/0316969443.0...
42,Me Talk Pretty One Day,David Sedaris,457,3.752735,http://images.amazon.com/images/P/0316776963.0...
46,Timeline,MICHAEL CRICHTON,552,3.750000,http://images.amazon.com/images/P/0345417623.0...
53,Angels &amp; Demons,Dan Brown,670,3.708955,http://images.amazon.com/images/P/0671027360.0...
58,The Poisonwood Bible: A Novel,Barbara Kingsolver,494,3.609312,http://images.amazon.com/images/P/0060930535.0...
59,The Pilot's Wife : A Novel,Anita Shreve,568,3.593310,http://images.amazon.com/images/P/0316601950.0...
60,1st to Die: A Novel,James Patterson,509,3.575639,http://images.amazon.com/images/P/0446610038.0...
62,She's Come Undone (Oprah's Book Club),Wally Lamb,468,3.570513,http://images.amazon.com/images/P/0671021001.0...
63,The Notebook,Nicholas Sparks,650,3.560000,http://images.amazon.com/images/P/0446605239.0...
68,Interview with the Vampire,Anne Rice,508,3.551181,http://images.amazon.com/images/P/0345337662.0...
70,The Nanny Diaries: A Novel,Emma McLaughlin,828,3.530193,http://images.amazon.com/images/P/0312278586.0...
72,Bridget Jones's Diary,Helen Fielding,815,3.527607,http://images.amazon.com/images/P/0330332775.0...
78,Divine Secrets of the Ya-Ya Sisterhood: A Novel,Rebecca Wells,740,3.437838,http://images.amazon.com/images/P/0060928336.0...
81,The Summons,John Grisham,655,3.432061,http://images.amazon.com/images/P/0440241073.0...
85,Jurassic Park,Michael Crichton,488,3.428279,http://images.amazon.com/images/P/0345370775.0...
92,Summer Sisters,Judy Blume,573,3.361257,http://images.amazon.com/images/P/0385324057.0...
96,The Partner,John Grisham,478,3.290795,http://images.amazon.com/images/P/0385472951.0...
100,Snow Falling on Cedars,David Guterson,662,3.252266,http://images.amazon.com/images/P/0151001006.0...
107,A Painted House,John Grisham,838,3.231504,http://images.amazon.com/images/P/044023722X.0...
112,Dreamcatcher,Stephen King,481,3.212058,http://images.amazon.com/images/P/0743211383.0...
124,The Testament,John Grisham,617,3.179903,http://images.amazon.com/images/P/0440234743.0...
131,The Girls' Guide to Hunting and Fishing,Melissa Bank,573,3.139616,http://images.amazon.com/images/P/0140293248.0...
135,A Time to Kill,JOHN GRISHAM,549,3.122040,http://images.amazon.com/images/P/0440211727.0...
142,The Client,John Grisham,483,3.084886,http://images.amazon.com/images/P/038542471X.0...
146,The Firm,John Grisham,569,3.080844,http://images.amazon.com/images/P/0385416342.0...
153,The Joy Luck Club,Amy Tan,555,3.055856,http://images.amazon.com/images/P/0804106304.0...
156,The King of Torts,John Grisham,458,3.039301,http://images.amazon.com/images/P/0385508042.0...
160,House of Sand and Fog,Andre Dubus III,588,3.030612,http://images.amazon.com/images/P/0375727345.0...
162,The Chamber,John Grisham,509,3.015717,http://images.amazon.com/images/P/0385424728.0...
167,The Reader,Bernhard Schlink,466,3.012876,http://images.amazon.com/images/P/0679442790.0...
172,The Rainmaker,JOHN GRISHAM,501,2.922156,http://images.amazon.com/images/P/044022165X.0...
179,The Runaway Jury,JOHN GRISHAM,520,2.880769,http://images.amazon.com/images/P/0440221471.0...
185,The Street Lawyer,JOHN GRISHAM,545,2.851376,http://images.amazon.com/images/P/0440225701.0...
190,The Brethren,JOHN GRISHAM,556,2.850719,http://images.amazon.com/images/P/0385497466.0...
195,Message in a Bottle,Nicholas Sparks,496,2.778226,http://images.amazon.com/images/P/0446523569.0...
200,Hannibal,Thomas Harris,468,2.760684,http://images.amazon.com/images/P/0440224675.0...
212,The Horse Whisperer,Nicholas Evans,507,2.686391,http://images.amazon.com/images/P/0440222656.0...
216,The Pelican Brief,John Grisham,581,2.611015,http://images.amazon.com/images/P/0440214041.0...

# Collaborative Filtering Based Reccomendation System

In [27]:
Ratings_with_name = ratings.merge(books, on='ISBN')

In [28]:
x = Ratings_with_name.groupby('User-ID')['Book-Rating'].count() > 200

In [29]:
user_index = x[x].index

In [30]:
filtered_rating = Ratings_with_name[Ratings_with_name['User-ID'].isin(user_index)]

In [31]:
y = filtered_rating.groupby('Book-Title').count()['Book-Rating'] > 50

In [32]:
movie_index = y[y].index

In [33]:
filtered_movie = filtered_rating[Ratings_with_name['Book-Title'].isin(movie_index)]

/var/folders/1q/9qf_f64j6md3l2bcpv0m427h0000gn/T/ipykernel_9378/20617591.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  filtered_movie = filtered_rating[Ratings_with_name['Book-Title'].isin(movie_index)]

In [34]:
filtered_movie

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
63,278418,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
65,3363,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
66,7158,0446520802,10,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
69,11676,0446520802,10,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
74,23768,0446520802,6,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
...,...,...,...,...,...,...,...,...,...,...
1026724,266865,0531001725,10,The Catcher in the Rye,Jerome David Salinger,1973,Scholastic Library Pub,http://images.amazon.com/images/P/0531001725.0...,http://images.amazon.com/images/P/0531001725.0...,http://images.amazon.com/images/P/0531001725.0...
1027923,269566,0670809381,0,Echoes,Maeve Binchy,1986,Penguin USA,http://images.amazon.com/images/P/0670809381.0...,http://images.amazon.com/images/P/0670809381.0...,http://images.amazon.com/images/P/0670809381.0...
1028777,271284,0440910927,0,The Rainmaker,John Grisham,1995,Island,http://images.amazon.com/images/P/0440910927.0...,http://images.amazon.com/images/P/0440910927.0...,http://images.amazon.com/images/P/0440910927.0...
1029070,271705,B0001PIOX4,0,Fahrenheit 451,Ray Bradbury,1993,Simon &amp; Schuster,http://images.amazon.com/images/P/B0001PIOX4.0...,http://images.amazon.com/images/P/B0001PIOX4.0...,http://images.amazon.com/images/P/B0001PIOX4.0...
1030868,275970,1586210661,9,Me Talk Pretty One Day,David Sedaris,2001,Time Warner Audio Major,http://images.amazon.com/images/P/1586210661.0...,http://images.amazon.com/images/P/1586210661.0...,http://images.amazon.com/images/P/1586210661.0...

In [35]:
pt = filtered_movie.pivot_table(index='Book-Title', columns='User-ID', values='Book-Rating')

In [36]:
pt.fillna(0, inplace =True)

In [37]:
pt

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Bend in the Road,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0

In [38]:
from sklearn.metrics.pairwise import cosine_similarity

In [39]:
similarity = cosine_similarity(pt)

In [40]:
similarity.shape

(679, 679)

In [69]:
def recommendation(book):
    book_index = np.where(pt.index == book)[0][0]
    similar_items = sorted(list(enumerate(similarity[book_index])), key= lambda x:x[1], reverse=True)[1:6]
    suggested_index = list(map(lambda x: x[0], similar_items))
    my_list = [x for x in pt.index[suggested_index]]
    print(my_list)

In [71]:
recommendation('A Bend in the Road')

['A Walk to Remember', 'The Last Time They Met : A Novel', 'Sea Glass: A Novel', 'Angels', 'Family Album']